spring.application.name=test-ecom-project
spring.datasource.url=jdbc:h2:mem:test-ecom-project

spring.datasource.username=vinayak
spring.datasource.password=orewaluffy
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl.auto=update
